"""init_schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-03 19:03:47.919563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('ad_language', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name'))
    )
    op.create_table('prompt_defaults',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('seeded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_defaults')),
    sa.UniqueConstraint('key', name=op.f('uq_prompt_defaults_key'))
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('key', name=op.f('uq_prompt_templates_key'))
    )
    op.create_table('ref_assets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('orig_name', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('style', 'logo')", name=op.f('ck_ref_assets_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_assets')),
    sa.UniqueConstraint('kind', 'sha256', name=op.f('uq_ref_assets_kind_sha256'))
    )
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_name', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('ad_language', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('ratio_choice', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('title_count', sa.SmallInteger(), server_default=sa.text('3'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_runs_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index('ix_runs_product_id', 'runs', ['product_id'], unique=False)
    op.create_index('ix_runs_updated_at', 'runs', ['updated_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('main_scene', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sub_scene', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sub_scene_desc', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('ratio', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('image_prompt', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('image_rel_path', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('derived_from_job_id', sa.BigInteger(), nullable=True),
    sa.Column('rev', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cur_version_seq', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['derived_from_job_id'], ['jobs.id'], name=op.f('fk_jobs_derived_from_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_jobs_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('run_id', 'filename', name=op.f('uq_jobs_run_id_filename')),
    sa.UniqueConstraint('run_id', 'seq', name=op.f('uq_jobs_run_id_seq'))
    )
    op.create_index('ix_jobs_derived_from_job_id', 'jobs', ['derived_from_job_id'], unique=False)
    op.create_table('run_ref_images',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind IN ('style', 'logo')", name=op.f('ck_run_ref_images_kind_valid')),
    sa.ForeignKeyConstraint(['asset_id'], ['ref_assets.id'], name=op.f('fk_run_ref_images_asset_id_ref_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_ref_images_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_ref_images')),
    sa.UniqueConstraint('run_id', 'kind', 'seq', name=op.f('uq_run_ref_images_run_id_kind_seq'))
    )
    op.create_index('ix_run_ref_images_asset_id', 'run_ref_images', ['asset_id'], unique=False)
    op.create_table('scene_lib',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('main_scene', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sub_scene', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('audience', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('trigger', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('pain_or_desire', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('product_use', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('product_fit', sa.SmallInteger(), nullable=True),
    sa.Column('visual_clarity', sa.SmallInteger(), nullable=True),
    sa.Column('purchase_intent', sa.SmallInteger(), nullable=True),
    sa.Column('attention_emotion', sa.SmallInteger(), nullable=True),
    sa.Column('meta_safety', sa.SmallInteger(), nullable=True),
    sa.Column('total_score', sa.SmallInteger(), nullable=True),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('in_ads', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_scene_lib_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_run_id'], ['runs.id'], name=op.f('fk_scene_lib_source_run_id_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_lib')),
    sa.UniqueConstraint('product_id', 'main_scene', 'sub_scene', name=op.f('uq_scene_lib_product_id_main_scene_sub_scene'))
    )
    op.create_index('ix_scene_lib_source_run_id', 'scene_lib', ['source_run_id'], unique=False)
    op.create_index('ix_scene_lib_total_score', 'scene_lib', ['total_score'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('main_scene', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sub_scene', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('audience', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('trigger', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('pain_or_desire', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('product_use', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('product_fit', sa.SmallInteger(), nullable=True),
    sa.Column('visual_clarity', sa.SmallInteger(), nullable=True),
    sa.Column('purchase_intent', sa.SmallInteger(), nullable=True),
    sa.Column('attention_emotion', sa.SmallInteger(), nullable=True),
    sa.Column('meta_safety', sa.SmallInteger(), nullable=True),
    sa.Column('total_score', sa.SmallInteger(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_scenes_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes')),
    sa.UniqueConstraint('run_id', 'seq', name=op.f('uq_scenes_run_id_seq'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_role_valid')),
    sa.CheckConstraint("scope IN ('scenes', 'prompt', 'image', 'copies')", name=op.f('ck_chat_messages_scope_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_chat_messages_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_chat_messages_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_job_id', 'chat_messages', ['job_id'], unique=False)
    op.create_index('uq_chat_messages_pos', 'chat_messages', ['run_id', 'scope', sa.literal_column('COALESCE(job_id, 0)'), 'seq'], unique=True)
    op.create_table('copies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('angle', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('headline', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('primary_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_copies_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copies')),
    sa.UniqueConstraint('job_id', 'seq', name=op.f('uq_copies_job_id_seq'))
    )
    op.create_table('image_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_image_versions_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_versions')),
    sa.UniqueConstraint('job_id', 'seq', name=op.f('uq_image_versions_job_id_seq'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_versions')
    op.drop_table('copies')
    op.drop_index('uq_chat_messages_pos', table_name='chat_messages')
    op.drop_index('ix_chat_messages_job_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('scenes')
    op.drop_index('ix_scene_lib_total_score', table_name='scene_lib')
    op.drop_index('ix_scene_lib_source_run_id', table_name='scene_lib')
    op.drop_table('scene_lib')
    op.drop_index('ix_run_ref_images_asset_id', table_name='run_ref_images')
    op.drop_table('run_ref_images')
    op.drop_index('ix_jobs_derived_from_job_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_runs_updated_at', table_name='runs')
    op.drop_index('ix_runs_product_id', table_name='runs')
    op.drop_table('runs')
    op.drop_table('ref_assets')
    op.drop_table('prompt_templates')
    op.drop_table('prompt_defaults')
    op.drop_table('products')
    # ### end Alembic commands ###
